// JOBS
const RECEIVE_JOBS = 'RECEIVE_JOBS';

// META INFO
const RECEIVE_JOB_ROLES = 'RECEIVE_JOB_ROLES';
const RECEIVE_SKILLS = 'RECEIVE_SKILLS';
const RECEIVE_MARKETS = 'RECEIVE_MARKETS';
const RECEIVE_CURRENCIES = 'RECEIVE_CURRENCIES';

export {
  RECEIVE_JOBS,
  RECEIVE_JOB_ROLES,
  RECEIVE_SKILLS,
  RECEIVE_MARKETS,
  RECEIVE_CURRENCIES
}
